apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-server
  name: todo-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              value: todo-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "todo-deall"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: ACCESS_TOKEN_SECRET
              value: "supersecretsecretaccess"
            - name: REFRESH_TOKEN_SECRET
              value: "supersecretsecretrefresh"
          image: jojonicho/node-todo-server:latest
          name: todo-server
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-server
  name: todo-server-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: todo-server
status:
  loadBalancer: {}

